# Generated by Django 3.2.6 on 2023-03-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentRegister', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Name', models.CharField(max_length=50, verbose_name='First Name')),
                ('Teacher_id', models.CharField(max_length=50, verbose_name='Lat Name')),
                ('Date_Of_Birth', models.DateField(max_length=50, null=True, verbose_name='Date Of Birth')),
                ('Faculty', models.CharField(max_length=50, verbose_name='Faculty')),
                ('Department', models.CharField(max_length=50, verbose_name='Department')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50, verbose_name='First Name')),
                ('Last_Name', models.CharField(max_length=50, verbose_name='Lat Name')),
                ('Date_Of_Birth', models.DateField(max_length=50, null=True, verbose_name='Date Of Birth')),
                ('Faculty', models.CharField(max_length=50, verbose_name='Faculty')),
                ('Department', models.CharField(max_length=50, verbose_name='Department')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='Course_Name',
        ),
    ]
