# Generated by Django 3.2.6 on 2023-03-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentRegister', '0002_auto_20230316_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Department',
            field=models.CharField(max_length=50, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Faculty',
            field=models.CharField(max_length=50, null=True, verbose_name='Faculty'),
        ),
        migrations.AlterField(
            model_name='student',
            name='First_Name',
            field=models.CharField(max_length=50, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Grade',
            field=models.CharField(max_length=50, null=True, verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Last_Name',
            field=models.CharField(max_length=50, null=True, verbose_name='Lat Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Unit_Name',
            field=models.CharField(max_length=50, null=True, verbose_name='Unit Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Year_Of_Study',
            field=models.CharField(max_length=50, null=True, verbose_name='Year of Study'),
        ),
    ]
