# Generated by Django 3.2.6 on 2023-03-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentRegister', '0004_alter_student_admission_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.AlterField(
            model_name='student',
            name='Last_Name',
            field=models.CharField(max_length=50, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Department',
            field=models.CharField(max_length=50, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Faculty',
            field=models.CharField(max_length=50, null=True, verbose_name='Faculty'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='First_Name',
            field=models.CharField(max_length=50, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Last_Name',
            field=models.CharField(max_length=50, null=True, verbose_name='Last Name'),
        ),
    ]
